// <auto-generated />
using System;
using Lizy.TerritorialDivisionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lizy.TerritorialDivisionService.Data.Migrations
{
    [DbContext(typeof(RegionDbContext))]
    partial class RegionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Lizy.TerritorialDivisionService.Data.Entities.County", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Counties");
                });

            modelBuilder.Entity("Lizy.TerritorialDivisionService.Data.Entities.Parish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CountyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.ToTable("Parishes");
                });

            modelBuilder.Entity("Lizy.TerritorialDivisionService.Data.Entities.SquareKilometer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Clients")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElderlyDensity")
                        .HasColumnType("int");

                    b.Property<double>("Inhabitants")
                        .HasColumnType("float");

                    b.Property<int>("KidDensity")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MaleDensity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Potential")
                        .HasColumnType("int");

                    b.Property<int>("WorkAgeDensity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParishId");

                    b.ToTable("SquareKilometers");
                });

            modelBuilder.Entity("Lizy.TerritorialDivisionService.Data.Entities.County", b =>
                {
                    b.OwnsOne("Lizy.TerritorialDivisionService.Data.Entities.Penetration", "Penetration", b1 =>
                        {
                            b1.Property<Guid>("CountyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PercentileFrom")
                                .HasColumnType("int")
                                .HasColumnName("PenetrationPercentileFrom");

                            b1.Property<int>("PercentileTill")
                                .HasColumnType("int")
                                .HasColumnName("PenetrationPercentileTill");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("Penetration");

                            b1.HasKey("CountyId");

                            b1.ToTable("Counties");

                            b1.WithOwner()
                                .HasForeignKey("CountyId");
                        });

                    b.Navigation("Penetration");
                });

            modelBuilder.Entity("Lizy.TerritorialDivisionService.Data.Entities.Parish", b =>
                {
                    b.HasOne("Lizy.TerritorialDivisionService.Data.Entities.County", "County")
                        .WithMany("Parishes")
                        .HasForeignKey("CountyId");

                    b.OwnsOne("Lizy.TerritorialDivisionService.Data.Entities.Penetration", "Penetration", b1 =>
                        {
                            b1.Property<Guid>("ParishId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PercentileFrom")
                                .HasColumnType("int")
                                .HasColumnName("PenetrationPercentileFrom");

                            b1.Property<int>("PercentileTill")
                                .HasColumnType("int")
                                .HasColumnName("PenetrationPercentileTill");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("Penetration");

                            b1.HasKey("ParishId");

                            b1.ToTable("Parishes");

                            b1.WithOwner()
                                .HasForeignKey("ParishId");
                        });

                    b.Navigation("County");

                    b.Navigation("Penetration");
                });

            modelBuilder.Entity("Lizy.TerritorialDivisionService.Data.Entities.SquareKilometer", b =>
                {
                    b.HasOne("Lizy.TerritorialDivisionService.Data.Entities.Parish", "Parish")
                        .WithMany("SquareKilometers")
                        .HasForeignKey("ParishId");

                    b.OwnsOne("Lizy.TerritorialDivisionService.Data.Entities.Penetration", "Penetration", b1 =>
                        {
                            b1.Property<Guid>("SquareKilometerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("PercentileFrom")
                                .HasColumnType("int")
                                .HasColumnName("PenetrationPercentileFrom");

                            b1.Property<int>("PercentileTill")
                                .HasColumnType("int")
                                .HasColumnName("PenetrationPercentileTill");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("Penetration");

                            b1.HasKey("SquareKilometerId");

                            b1.ToTable("SquareKilometers");

                            b1.WithOwner()
                                .HasForeignKey("SquareKilometerId");
                        });

                    b.Navigation("Parish");

                    b.Navigation("Penetration");
                });

            modelBuilder.Entity("Lizy.TerritorialDivisionService.Data.Entities.County", b =>
                {
                    b.Navigation("Parishes");
                });

            modelBuilder.Entity("Lizy.TerritorialDivisionService.Data.Entities.Parish", b =>
                {
                    b.Navigation("SquareKilometers");
                });
#pragma warning restore 612, 618
        }
    }
}
